name: Deploy Next.js to GitHub Pages

on:
  push:
    branches:
      - main # Change this to your default branch
  pull_request:
    branches:
      - main # Optionally run on PRs to main as well

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '23' # Ensure the Node.js version is compatible with your project
          cache: 'pnpm'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Export to static HTML
        run: pnpm run export

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out # Ensure this matches your Next.js export directory

